#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TwilioVideoRoomsAdvancedCameraCapturerSampleAndroid.Resource", IsApplication=true)]

namespace TwilioVideoRoomsAdvancedCameraCapturerSampleAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040002
			public const int take_picture_button = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int toggle_flash_button = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int video_view = 2130968576;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int activity_advanced_camera_capturer = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int picture_image_view = 2130837505;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030005
			public const int camera_capturer_picture = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int close = 2130903046;
			
			// aapt resource value: 0x7f030002
			public const int flash_not_supported = 2130903042;
			
			// aapt resource value: 0x7f030000
			public const int permissions_needed = 2130903040;
			
			// aapt resource value: 0x7f030003
			public const int take_picture = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int take_picture_failed = 2130903044;
			
			// aapt resource value: 0x7f030001
			public const int toggle_flash = 2130903041;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
