#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TwilioVideoRoomsQuickStartMainSampleAndroid.Resource", IsApplication=true)]

namespace TwilioVideoRoomsQuickStartMainSampleAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f020001
			public const int action_settings = 2130837505;
			
			// aapt resource value: 0x7f020000
			public const int app_name = 2130837504;
			
			// aapt resource value: 0x7f020003
			public const int error_retrieving_access_token = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int log_out = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int permissions_needed = 2130837509;
			
			// aapt resource value: 0x7f020002
			public const int room_status = 2130837506;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
